/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    id("com.gradleup.shadow") version "9.0.0-beta11"
    `maven-publish`
}

repositories {
    mavenLocal()
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://oss.sonatype.org/content/groups/public/")
    maven("https://repo.azisaba.net/repository/maven-public/")
    maven("https://jitpack.io")
    maven("https://repo.codemc.io/repository/maven-public/")
    maven("https://repo.maven.apache.org/maven2/")

}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.8-R0.1-SNAPSHOT")
    compileOnly(libs.dev.felnull.bettergui)
    compileOnly(libs.dev.felnull.betterstorage)
    compileOnly(libs.com.github.milkbowl.vaultapi)
    compileOnly(libs.de.tr7zw.item.nbt.api.plugin)
}

group = "dev.felnull"
version = "1.1.0-SNAPSHOT"

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

tasks {
    processResources {
        filteringCharset = "UTF-8"
        from(sourceSets.main.get().resources.srcDirs) {
            include("**")

            val tokenReplacementMap = mapOf(
                "version" to project.version,
                "name" to project.rootProject.name,
            )

            filter<org.apache.tools.ant.filters.ReplaceTokens>("tokens" to tokenReplacementMap)
        }

        duplicatesStrategy = DuplicatesStrategy.INCLUDE

        from(projectDir) { include("LICENSE") }
    }

    compileJava {
        options.encoding = "UTF-8"
    }

     shadowJar {
         archiveClassifier.set("")
     }
}
