name: StorageGUI
version: @version@
main: dev.felnull.storagegui.StorageGUI
api-version: '1.16'
depend:
  - BetterGUI
  - BetterStorage
  - Vault
commands:
  showstoragesoundlist:
    permission: storagegui.command.admin
    aliases: [sssl]
  soundreload:
    permission: storagegui.command.admin
  shownowstoragesound:
    permission: storagegui.command.admin
    aliases: [ snss ]
  createuniqueitem:
    permission: storagegui.command.admin
    aliases: [ createuni ]
  vault:
    permission: storagegui.command.user
    aliases:
      - storage
      - str
  guireload:
    permission: storagegui.command.admin
permissions:
  storagegui.command.admin:
    default: op
  storagegui.command.user:
    default: true